### ISSUE TITLE
todo: cleanup syntax option --sharedfolder

### ISSUE THREAD

**Issue by mzemb** [aacebedo/machination#12]
I'll prefer --sharedfolder <path>:<path>
(instead the use of pipe as a separator)

**Comment by mzemb** [comment]
And ideallly I would like a quicker syntax: if I don't specify a mount point, machination shall use the host path.
Ie:
--sharedfolder .
should be equilavent to
--sharefolder "$(pwd)|$(pwd)"

**Comment by aacebedo** [comment]
Pipe removed. 
Not agree about the shortcut for pwd
