### ISSUE TITLE
[todo] machine infos ip behaviour

### ISSUE THREAD

**Issue by mzemb** [aacebedo/machination#31]
note: ip address is only shown if machine is running (ie not stopped)

**Comment by mzemb** [comment]
Actually there is an incoherence between the infos printed and the ifconfig inside container.
expected action: fix or explain

> machination infos XXX 
> Retrieving information for machine instance 'XXX'
>   Name: XXX
>   Architecture: x64
>   Provisioner: ansible
>   Provider: docker
>   Primary IPAddress of the container: 172.17.0.124
>   State: Running
>   Network interfaces:
> - Name: eth0
>   IPAddress: 172.17.0.200
>   Host interface: eth0
>   Hostname: 
> - Name: eth1
>   IPAddress: 172.17.0.201
>   Host interface: eth0
>   Hostname: eth1

[vagrant@machination-XXX ~ ]$ ifconfig 
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:7c  
inet addr:172.17.0.124  Bcast:0.0.0.0  Mask:255.255.0.0
eth1      Link encap:Ethernet  HWaddr 00:16:3e:4c:fc:e5  
inet addr:172.17.0.200  Bcast:0.0.0.0  Mask:255.255.255.0
eth2      Link encap:Ethernet  HWaddr 00:16:3e:23:9b:02  
inet addr:172.17.0.201  Bcast:0.0.0.0  Mask:255.255.255.0

**Comment by mzemb** [comment]
TODO:
1) correct ethX counter
2) show all ips adresses in machine infos (and maybe show a line n/a while stopped)

**Comment by aacebedo** [comment]
Done
