### ISSUE TITLE
[discuss] syntax of --guestinterface opt ?

### ISSUE THREAD

**Issue by mzemb** [aacebedo/machination#32]
> machination create -h
> IMHO adding an interface and adding a sharedfolder should have the same syntax (and separator, but guestinterface still uses the pipe).
>   --guestinterface GUESTINTERFACE, -i GUESTINTERFACE
>                         Network interface to add to the new machine
>                         <hostinterface|ip_addr|mac_addr|hostname> |
>                         <hostinterface|ip_addr|mac_addr>
>   --sharedfolder SHAREDFOLDER SHAREDFOLDER, -s SHAREDFOLDER SHAREDFOLDER
>                         Shared folder between the new machine and the host
>                         <host_folder guest_folder>

**Comment by mzemb** [comment]
Don't know how to use option. I tried:

--guestinterface eth0 172.17.0.200
which fails with "Machination create: error: argument template: invalid choice: '172.17.0.200' (choose from '<template-name>v:1.0', '<template-name>:1.0', '<template-name>:1.0', '<template-name>:1.0')"

--guestinterface "eth0|172.17.0.200"
which fails with "Unable to create machine instance 'XXX': object of type 'int' has no len()."

**Comment by mzemb** [comment]
TODO: rewrite help string to explain that there is two possible usages

**Comment by mzemb** [comment]
Note, correct usage with current version: 
--guestinterface "eth0|192.168.0.100|00:01:02:03:04:05"

**Comment by mzemb** [comment]
Todo:
1) clarify usage (two possible)
2) usage of pipe
3) mac addr should be optionnal

**Comment by aacebedo** [comment]
Done
