### ISSUE TITLE
[feature] arg modification: accept lists and --all by default

### ISSUE THREAD

**Issue by mzemb** [aacebedo/machination#34]
It would be nice to have cmd

> machination list
> act as 
> machination list templates + machination list instances

**Comment by mzemb** [comment]
In the same way, it would be nice by default to list infos for all instances

> machination infos

**Comment by mzemb** [comment]
In fact all commands that take one instance should accept a list of instances and use all as default if nothing is given.

**Comment by aacebedo** [comment]
Done
